apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopspractices.crd.com
spec:
  group: crd.com
  names:
    plural: devopspractices
    singular: devopspractice
    kind: DevopsPractice
    shortNames:
      - dop
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "This is the name of the practice set"
                duration:
                  type: string
                  description: "This is the duration of the practice set"
                mode:
                  type: string
                  description: "This is the mode of pratice"
                platform:
                  type: string
                  description: "This is the platform of the practice set."
