apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: nginx-ns
  labels:
    app: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data

