apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: nginx-ns
  labels:
    app: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
