apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: apache-deployment
