apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: nginx-ns
  labels:
    app.kubernetes.io/name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-daemonset
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-daemonset
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
