apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx-ns
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
        - name: batch-cont
          image: busybox:latest
          command: ["sh", "-c", "echo Hello Dosto! && sleep 10"]
      restartPolicy: Never
