apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app.kubernetes.io/name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  tolerations:
    - key: prod
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
